#include "langdefs.h"

#define ENUMSTRING(enum) \
  static char enum##_str[] = #enum ;

ENUMSTRING(NONE)
ENUMSTRING(LOCAL)
ENUMSTRING(GLOBAL)
ENUMSTRING(INSTVAR)
ENUMSTRING(CLASSVAR)
ENUMSTRING(NUMBER)
ENUMSTRING(BLOCK)
ENUMSTRING(END)
ENUMSTRING(PRINT)

ENUMSTRING(ADD)
ENUMSTRING(UADD)
ENUMSTRING(SUB)
ENUMSTRING(USUB)
ENUMSTRING(MUL)
ENUMSTRING(DIV)
ENUMSTRING(FDIV)
ENUMSTRING(MOD)
ENUMSTRING(ASHFTL)
ENUMSTRING(ASHFTR)
ENUMSTRING(LSHFTL)
ENUMSTRING(LSHFTR)
ENUMSTRING(BITAND)
ENUMSTRING(BITOR)
ENUMSTRING(BITXOR)
ENUMSTRING(BITNOT)

ENUMSTRING(SINE)
ENUMSTRING(COSINE)
ENUMSTRING(LOG_E)
ENUMSTRING(LOG_2)
ENUMSTRING(LOG_10)

ENUMSTRING(LPAREN)
ENUMSTRING(RPAREN)

ENUMSTRING(CMP)
ENUMSTRING(NEQ)
ENUMSTRING(EQ)
ENUMSTRING(LT)
ENUMSTRING(GT)
ENUMSTRING(LEQ)
ENUMSTRING(GEQ)
ENUMSTRING(LOGAND)
ENUMSTRING(LOGOR)
ENUMSTRING(LOGNOT)

ENUMSTRING(ASSIGN)

ENUMSTRING(PUSH)

static char dunno[] = "????????";

#define ENUMCASE(enum)\
  case KL_##enum :\
    return enum##_str ;

char* kl_langdef_name(int value) {
  switch (value) {
    ENUMCASE(NONE)
    ENUMCASE(LOCAL)
    ENUMCASE(GLOBAL)
    ENUMCASE(INSTVAR)
    ENUMCASE(CLASSVAR)
    ENUMCASE(NUMBER)
    ENUMCASE(BLOCK)
    ENUMCASE(END)
    ENUMCASE(PRINT)

    ENUMCASE(ADD)
    ENUMCASE(UADD)
    ENUMCASE(SUB)
    ENUMCASE(USUB)
    ENUMCASE(MUL)
    ENUMCASE(DIV)
    ENUMCASE(FDIV)
    ENUMCASE(MOD)
    ENUMCASE(ASHFTL)
    ENUMCASE(ASHFTR)
    ENUMCASE(LSHFTL)
    ENUMCASE(LSHFTR)
    ENUMCASE(BITAND)
    ENUMCASE(BITOR)
    ENUMCASE(BITXOR)
    ENUMCASE(BITNOT)

    ENUMCASE(SINE)
    ENUMCASE(COSINE)
    ENUMCASE(LOG_E)
    ENUMCASE(LOG_2)
    ENUMCASE(LOG_10)

    ENUMCASE(LPAREN)
    ENUMCASE(RPAREN)

    ENUMCASE(CMP)
    ENUMCASE(NEQ)
    ENUMCASE(EQ)
    ENUMCASE(LT)
    ENUMCASE(GT)
    ENUMCASE(LEQ)
    ENUMCASE(GEQ)
    ENUMCASE(LOGAND)
    ENUMCASE(LOGOR)
    ENUMCASE(LOGNOT)

    ENUMCASE(ASSIGN)

    ENUMCASE(PUSH)

    default:
      return dunno;
  }
}
